version: "3.8"

services:
  mysql:
    build:
        context: .
        dockerfile: db.dockerfile
    container_name: mysql_gameswap_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gameswap_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
